# Generated by Django 5.0.1 on 2024-01-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_summary_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='summary',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
