# Generated by Django 5.0.1 on 2024-01-16 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0021_remove_experience_company_experience_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='company',
        ),
        migrations.AddField(
            model_name='achievement',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_achievements', to='resume.company'),
        ),
    ]
