# Generated by Django 5.0.1 on 2024-01-16 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0022_remove_achievement_company_achievement_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='date',
            new_name='title',
        ),
    ]
