# Generated by Django 5.0.1 on 2024-01-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0023_rename_date_achievement_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('major', models.CharField(blank=True, max_length=200, null=True)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
