# Generated by Django 5.0.1 on 2024-01-16 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0024_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='end_date',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_date',
        ),
    ]
