# Generated by Django 5.0.1 on 2024-01-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0025_rename_end_date_education_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_cert', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
